language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ncbi-blast+
  - sudo apt-get install libdb-dev
  - sudo apt-get install graphviz
  - cpanm BioPerl 
  - cpanm Bio::Tools::Run::StandAloneBlastPlus --force
  - cpanm Moose
  - cpanm Template
  - cpanm Try::Tiny
  - cpanm Math::Trig
  - cpanm File::Temp
  - cpanm File::Slurp
  - wget https://github.com/hyattpd/Prodigal/archive/v2.6.1.tar.gz -O /tmp/prodigal.tar.gz
  - tar -xvf /tmp/prodigal.tar.gz
  - cd Prodigal-2.6.1
  - sudo make install
  - cd ..
install: true

